import type { Face } from '../Face'
import type { CardProvider } from './providers'
import { shuffle } from './words'

export const gcpIcons: CardProvider = {
  id: 'gcp-icons',
  label: 'GCP Icons', group: 'symbols', difficulty: 'tough',
  icon: '☁️',
  description: 'Google Cloud product icons in full colour',
  source: 'GCP Icons', sourceUrl: 'https://gcpicons.com',
  fetch,
}

// [icon slug, display name] for the official Google Cloud product icon set (the
// same catalogue behind gcpicons.com). Slugs are the Iconify `gcp` set keys;
// the full-colour SVGs are served per-icon by the Iconify API.
const ICONS: [string, string][] = [
  ["access-context-manager", "Access Context Manager"], ["administration", "Administration"], ["advanced-agent-modeling", "Advanced Agent Modeling"],
  ["advanced-solutions-lab", "Advanced Solutions Lab"], ["agent-assist", "Agent Assist"], ["ai-hub", "AI Hub"],
  ["ai-platform", "AI Platform"], ["ai-platform-unified", "AI Platform Unified"], ["analytics-hub", "Analytics Hub"],
  ["anthos", "Anthos"], ["anthos-config-management", "Anthos Config Management"], ["anthos-service-mesh", "Anthos Service Mesh"],
  ["api", "API"], ["api-analytics", "API Analytics"], ["api-monetization", "API Monetization"],
  ["apigee-api-platform", "Apigee API Platform"], ["apigee-sense", "Apigee Sense"], ["app-engine", "App Engine"],
  ["artifact-registry", "Artifact Registry"], ["asset-inventory", "Asset Inventory"], ["assured-workloads", "Assured Workloads"],
  ["automl", "AutoML"], ["automl-natural-language", "AutoML Natural Language"], ["automl-tables", "AutoML Tables"],
  ["automl-translation", "AutoML Translation"], ["automl-video-intelligence", "AutoML Video Intelligence"], ["automl-vision", "AutoML Vision"],
  ["bare-metal-solutions", "Bare Metal Solutions"], ["batch", "Batch"], ["beyondcorp", "BeyondCorp"],
  ["bigquery", "BigQuery"], ["bigtable", "Bigtable"], ["billing", "Billing"],
  ["binary-authorization", "Binary Authorization"], ["catalog", "Catalog"], ["certificate-authority-service", "Certificate Authority Service"],
  ["certificate-manager", "Certificate Manager"], ["cloud-api-gateway", "Cloud API Gateway"], ["cloud-apis", "Cloud APIs"],
  ["cloud-armor", "Cloud Armor"], ["cloud-asset-inventory", "Cloud Asset Inventory"], ["cloud-audit-logs", "Cloud Audit Logs"],
  ["cloud-build", "Cloud Build"], ["cloud-cdn", "Cloud CDN"], ["cloud-code", "Cloud Code"],
  ["cloud-composer", "Cloud Composer"], ["cloud-data-fusion", "Cloud Data Fusion"], ["cloud-deploy", "Cloud Deploy"],
  ["cloud-deployment-manager", "Cloud Deployment Manager"], ["cloud-dns", "Cloud DNS"], ["cloud-domains", "Cloud Domains"],
  ["cloud-ekm", "Cloud EKM"], ["cloud-endpoints", "Cloud Endpoints"], ["cloud-external-ip-addresses", "Cloud External IP Addresses"],
  ["cloud-firewall-rules", "Cloud Firewall Rules"], ["cloud-for-marketing", "Cloud for Marketing"], ["cloud-functions", "Cloud Functions"],
  ["cloud-generic", "Cloud Generic"], ["cloud-gpu", "Cloud GPU"], ["cloud-healthcare-api", "Cloud Healthcare API"],
  ["cloud-healthcare-marketplace", "Cloud Healthcare Marketplace"], ["cloud-hsm", "Cloud HSM"], ["cloud-ids", "Cloud IDS"],
  ["cloud-inference-api", "Cloud Inference API"], ["cloud-interconnect", "Cloud Interconnect"], ["cloud-jobs-api", "Cloud Jobs API"],
  ["cloud-load-balancing", "Cloud Load Balancing"], ["cloud-logging", "Cloud Logging"], ["cloud-media-edge", "Cloud Media Edge"],
  ["cloud-monitoring", "Cloud Monitoring"], ["cloud-nat", "Cloud NAT"], ["cloud-natural-language-api", "Cloud Natural Language API"],
  ["cloud-network", "Cloud Network"], ["cloud-ops", "Cloud Ops"], ["cloud-optimization-ai", "Cloud Optimization AI"],
  ["cloud-optimization-ai-fleet-routing-api", "Cloud Optimization AI Fleet Routing API"], ["cloud-router", "Cloud Router"], ["cloud-routes", "Cloud Routes"],
  ["cloud-run", "Cloud Run"], ["cloud-run-for-anthos", "Cloud Run for Anthos"], ["cloud-scheduler", "Cloud Scheduler"],
  ["cloud-security-scanner", "Cloud Security Scanner"], ["cloud-shell", "Cloud Shell"], ["cloud-spanner", "Cloud Spanner"],
  ["cloud-sql", "Cloud SQL"], ["cloud-storage", "Cloud Storage"], ["cloud-tasks", "Cloud Tasks"],
  ["cloud-test-lab", "Cloud Test Lab"], ["cloud-tpu", "Cloud TPU"], ["cloud-translation-api", "Cloud Translation API"],
  ["cloud-vision-api", "Cloud Vision API"], ["cloud-vpn", "Cloud VPN"], ["compute-engine", "Compute Engine"],
  ["configuration-management", "Configuration Management"], ["connectivity-test", "Connectivity Test"], ["connectors", "Connectors"],
  ["contact-center-ai", "Contact Center AI"], ["container-optimized-os", "Container Optimized OS"], ["container-registry", "Container Registry"],
  ["data-catalog", "Data Catalog"], ["data-labeling", "Data Labeling"], ["data-layers", "Data Layers"],
  ["data-loss-prevention-api", "Data Loss Prevention API"], ["data-qna", "Data QnA"], ["data-studio", "Data Studio"],
  ["data-transfer", "Data Transfer"], ["database-migration-service", "Database Migration Service"], ["dataflow", "Dataflow"],
  ["datalab", "Datalab"], ["dataplex", "Dataplex"], ["datapol", "Datapol"],
  ["dataprep", "Dataprep"], ["dataproc", "Dataproc"], ["dataproc-metastore", "Dataproc Metastore"],
  ["datashare", "Datashare"], ["datastore", "Datastore"], ["datastream", "Datastream"],
  ["debugger", "Debugger"], ["developer-portal", "Developer Portal"], ["dialogflow-cx", "Dialogflow CX"],
  ["dialogflow-insights", "Dialogflow Insights"], ["document-ai", "Document AI"], ["early-access-center", "Early Access Center"],
  ["error-reporting", "Error Reporting"], ["eventarc", "Eventarc"], ["filestore", "Filestore"],
  ["financial-services-marketplace", "Financial Services Marketplace"], ["firestore", "Firestore"], ["fleet-engine", "Fleet Engine"],
  ["free-trial", "Free Trial"], ["game-servers", "Game Servers"], ["gce-systems-management", "GCE Systems Management"],
  ["genomics", "Genomics"], ["gke-on-prem", "GKE on Prem"], ["google-cloud-marketplace", "Google Cloud Marketplace"],
  ["google-kubernetes-engine", "Google Kubernetes Engine"], ["google-maps-platform", "Google Maps Platform"], ["healthcare-nlp-api", "Healthcare NLP API"],
  ["home", "Home"], ["identity-and-access-management", "Identity and Access Management"], ["identity-aware-proxy", "Identity Aware Proxy"],
  ["identity-platform", "Identity Platform"], ["iot-core", "IoT Core"], ["iot-edge", "IoT Edge"],
  ["key-access-justifications", "Key Access Justifications"], ["key-management-service", "Key Management Service"], ["kuberun", "KubeRun"],
  ["launcher", "Launcher"], ["local-ssd", "Local SSD"], ["managed-service-for-microsoft-active-directory", "Managed Service for Microsoft Active Directory"],
  ["media-translation-api", "Media Translation API"], ["memorystore", "Memorystore"], ["migrate-for-anthos", "Migrate for Anthos"],
  ["migrate-for-compute-engine", "Migrate for Compute Engine"], ["my-cloud", "My Cloud"], ["network-connectivity-center", "Network Connectivity Center"],
  ["network-intelligence-center", "Network Intelligence Center"], ["network-security", "Network Security"], ["network-tiers", "Network Tiers"],
  ["network-topology", "Network Topology"], ["onboarding", "Onboarding"], ["os-configuration-management", "OS Configuration Management"],
  ["os-inventory-management", "OS Inventory Management"], ["os-patch-management", "OS Patch Management"], ["partner-interconnect", "Partner Interconnect"],
  ["partner-portal", "Partner Portal"], ["performance-dashboard", "Performance Dashboard"], ["permissions", "Permissions"],
  ["persistent-disk", "Persistent Disk"], ["phishing-protection", "Phishing Protection"], ["policy-analyzer", "Policy Analyzer"],
  ["premium-network-tier", "Premium Network Tier"], ["private-connectivity", "Private Connectivity"], ["private-service-connect", "Private Service Connect"],
  ["producer-portal", "Producer Portal"], ["profiler", "Profiler"], ["project", "Project"],
  ["pubsub", "Pub/Sub"], ["quantum-engine", "Quantum Engine"], ["quotas", "Quotas"],
  ["real-world-insights", "Real World Insights"], ["recommendations-ai", "Recommendations AI"], ["release-notes", "Release Notes"],
  ["retail-api", "Retail API"], ["risk-manager", "Risk Manager"], ["runtime-config", "Runtime Config"],
  ["secret-manager", "Secret Manager"], ["security", "Security"], ["security-command-center", "Security Command Center"],
  ["security-health-advisor", "Security Health Advisor"], ["security-key-enforcement", "Security Key Enforcement"], ["service-discovery", "Service Discovery"],
  ["speech-to-text", "Speech to Text"], ["stackdriver", "Stackdriver"], ["standard-network-tier", "Standard Network Tier"],
  ["stream-suite", "Stream Suite"], ["support", "Support"], ["tensorflow-enterprise", "TensorFlow Enterprise"],
  ["text-to-speech", "Text to Speech"], ["tools-for-powershell", "Tools for PowerShell"], ["trace", "Trace"],
  ["traffic-director", "Traffic Director"], ["transfer", "Transfer"], ["transfer-appliance", "Transfer Appliance"],
  ["user-preferences", "User Preferences"], ["vertexai", "Vertex AI"], ["video-intelligence-api", "Video Intelligence API"],
  ["virtual-private-cloud", "Virtual Private Cloud"], ["visual-inspection", "Visual Inspection"], ["vmware-engine", "VMware Engine"],
  ["web-risk", "Web Risk"], ["web-security-scanner", "Web Security Scanner"], ["workflows", "Workflows"],
  ["workload-identity-pool", "Workload Identity Pool"],]

async function fetch(): Promise<Face[]> {
  return shuffle(ICONS)
    .slice(0, 20)
    .map(([slug, name]) => ({
      kind: 'image',
      url: `https://api.iconify.design/gcp/${slug}.svg`,
      fit: 'contain',
      tooltip: name,
      link: 'https://gcpicons.com',
    }))
}
