import type { Face } from '../Face'
import type { Deck } from './deck'
import { shuffle } from '../shuffle'

export const flags: Deck = {
  id: 'flags',
  label: 'Flags',
  group: 'symbols',
  difficulty: 'brutal',
  icon: '🌍',
  description: 'Country flags from around the world',
  fetch,
}

const FLAGS: [string, string][] = [
  ['🇬🇧', 'United Kingdom'],
  ['🇫🇷', 'France'],
  ['🇩🇪', 'Germany'],
  ['🇮🇹', 'Italy'],
  ['🇪🇸', 'Spain'],
  ['🇵🇹', 'Portugal'],
  ['🇳🇱', 'Netherlands'],
  ['🇧🇪', 'Belgium'],
  ['🇨🇭', 'Switzerland'],
  ['🇦🇹', 'Austria'],
  ['🇸🇪', 'Sweden'],
  ['🇳🇴', 'Norway'],
  ['🇩🇰', 'Denmark'],
  ['🇫🇮', 'Finland'],
  ['🇮🇪', 'Ireland'],
  ['🇵🇱', 'Poland'],
  ['🇬🇷', 'Greece'],
  ['🇨🇿', 'Czechia'],
  ['🇭🇺', 'Hungary'],
  ['🇷🇴', 'Romania'],
  ['🇺🇦', 'Ukraine'],
  ['🇷🇺', 'Russia'],
  ['🇮🇸', 'Iceland'],
  ['🇭🇷', 'Croatia'],
  ['🇺🇸', 'United States'],
  ['🇨🇦', 'Canada'],
  ['🇲🇽', 'Mexico'],
  ['🇧🇷', 'Brazil'],
  ['🇦🇷', 'Argentina'],
  ['🇨🇱', 'Chile'],
  ['🇨🇴', 'Colombia'],
  ['🇵🇪', 'Peru'],
  ['🇺🇾', 'Uruguay'],
  ['🇻🇪', 'Venezuela'],
  ['🇨🇺', 'Cuba'],
  ['🇯🇲', 'Jamaica'],
  ['🇯🇵', 'Japan'],
  ['🇨🇳', 'China'],
  ['🇰🇷', 'South Korea'],
  ['🇮🇳', 'India'],
  ['🇹🇭', 'Thailand'],
  ['🇻🇳', 'Vietnam'],
  ['🇵🇭', 'Philippines'],
  ['🇮🇩', 'Indonesia'],
  ['🇲🇾', 'Malaysia'],
  ['🇸🇬', 'Singapore'],
  ['🇵🇰', 'Pakistan'],
  ['🇧🇩', 'Bangladesh'],
  ['🇮🇱', 'Israel'],
  ['🇸🇦', 'Saudi Arabia'],
  ['🇦🇪', 'United Arab Emirates'],
  ['🇹🇷', 'Turkey'],
  ['🇮🇷', 'Iran'],
  ['🇮🇶', 'Iraq'],
  ['🇳🇵', 'Nepal'],
  ['🇿🇦', 'South Africa'],
  ['🇪🇬', 'Egypt'],
  ['🇳🇬', 'Nigeria'],
  ['🇰🇪', 'Kenya'],
  ['🇲🇦', 'Morocco'],
  ['🇬🇭', 'Ghana'],
  ['🇪🇹', 'Ethiopia'],
  ['🇹🇳', 'Tunisia'],
  ['🇩🇿', 'Algeria'],
  ['🇸🇳', 'Senegal'],
  ['🇦🇺', 'Australia'],
  ['🇳🇿', 'New Zealand'],
  ['🇫🇯', 'Fiji'],
]

async function fetch(total = 20): Promise<Face[]> {
  return shuffle(FLAGS)
    .slice(0, total)
    .map(([flag, country]) => ({ kind: 'glyph', text: flag, tooltip: country }))
}
